format = "[┌─$all](dimmed white) "

[character]
format = "[└─](dimmed white)$symbol"
success_symbol = "[\\$](bold blue)"

[directory]
style = "bold blue"
format = "\\([$path]($style)[$read_only]($read_only_style)\\) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[aws]
disabled = true
style = "bold white"